// Rebuilds crates/pm/views/vendor/ from the exact versions in package.json
// (AGT-1403). Run from this directory:
//
//   bun install --frozen-lockfile && bun build.ts
//
// and commit the output. Nothing here runs during `cargo build`: pm embeds
// the committed files (crates/pm/src/app/views.rs), and ui-leaf bundles
// them into the ticket view at mount time, so installing pm never needs a
// JavaScript toolchain or network access.
//
// Two files come out:
//
// - vendor/loro.js — loro-crdt's `base64` build copied verbatim: the wasm
//   module inlined as base64 and compiled in-page. ui-leaf serves a view as
//   one HTML page with no static assets, so a `.wasm` file next to the JS
//   could never be fetched. Compiling it needs `'wasm-unsafe-eval'` in the
//   page's script-src (crates/pm/src/app/launch.rs).
// - vendor/codemirror.js — codemirror.ts, bundled and minified, with every
//   `loro-crdt` import rewritten to `./loro.js`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const out = join(import.meta.dir, "..", "views", "vendor");
mkdirSync(out, { recursive: true });
const pkg = JSON.parse(readFileSync(join(import.meta.dir, "package.json"), "utf8"));
const deps: Record<string, string> = pkg.dependencies;
const pins = Object.entries(deps)
  .map(([name, version]) => `${name}@${version}`)
  .join(", ");

const loro = readFileSync(
  join(import.meta.dir, "node_modules", "loro-crdt", "base64", "index.js"),
  "utf8",
);
writeFileSync(
  join(out, "loro.js"),
  `// GENERATED by crates/pm/views-vendor/build.ts — do not edit.\n` +
    `// loro-crdt@${deps["loro-crdt"]} (MIT, https://github.com/loro-dev/loro), base64 build.\n` +
    loro,
);

const result = await Bun.build({
  entrypoints: [join(import.meta.dir, "codemirror.ts")],
  target: "browser",
  format: "esm",
  minify: true,
  external: ["loro-crdt"],
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
// Bun keeps an external's specifier as written: point it at the sibling.
const bundled = await result.outputs[0].text();
const js = bundled.replace(/(from\s*)(["'])loro-crdt\2/g, '$1"./loro.js"');
if (/["']loro-crdt["']/.test(js)) {
  console.error("codemirror.js still imports loro-crdt by name");
  process.exit(1);
}
writeFileSync(
  join(out, "codemirror.js"),
  `// GENERATED by crates/pm/views-vendor/build.ts — do not edit.\n` +
    `// Bundles (all MIT): ${pins}.\n` +
    js,
);
console.log(`wrote ${out}/loro.js and ${out}/codemirror.js`);
